name: uep239Final
channels:
  - conda-forge
dependencies:
  - python=3.*
  - ipython=7.10.*
  - jupyterlab=3.*
  - scipy
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - rasterio
  - richdem
  - rasterstats
  - contextily
